networks:
  sandbox-internal:
    name: sandbox-internal
    external: true
  default: {}

volumes:
  ollama:
    external: true

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    ports:
      - "11434:11434"
    networks:
      - default
      - sandbox-internal
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
